"""Catalog, read, and generate research reports."""

from datetime import UTC, datetime
from pathlib import Path

from backend.schemas.report import ReportContent, ReportItem
from backend.services.backtests import read_backtest_job, read_backtest_result
from marketlab.reporting.report import ResearchReport, write_research_report

REPORT_ROOT = Path("reports")
TEXT_FORMATS = {"md", "html", "json", "csv", "txt"}


def report_catalog(project_root: Path = Path(".")) -> list[ReportItem]:
    root = (project_root.resolve() / REPORT_ROOT).resolve()
    if not root.is_dir():
        return []
    items = [_item(path, root) for path in root.rglob("*") if _visible_file(path)]
    return sorted(items, key=lambda item: item.updated_at, reverse=True)


def report_content(relative_path: str, project_root: Path = Path(".")) -> ReportContent:
    root = (project_root.resolve() / REPORT_ROOT).resolve()
    path = (root / relative_path).resolve()
    if root not in path.parents or not _visible_file(path):
        raise FileNotFoundError(relative_path)
    if path.suffix.lower().lstrip(".") not in TEXT_FORMATS:
        raise ValueError("report format cannot be previewed")
    if path.stat().st_size > 1_000_000:
        raise ValueError("report is too large to preview")
    return ReportContent(
        report=_item(path, root), content=path.read_text(encoding="utf-8")
    )


def generate_backtest_report(experiment_id: str) -> list[ReportItem]:
    job = read_backtest_job(experiment_id)
    result = read_backtest_result(experiment_id)
    metrics = result["metrics"]
    strategy = str(result["strategy"])
    report = ResearchReport(
        title=f"{strategy.replace('_', ' ').title()} Research Report",
        hypothesis=(
            f"Evaluate whether the {strategy.replace('_', ' ')} strategy survives "
            "realistic costs and benchmark comparison."
        ),
        experiment_id=experiment_id,
        configuration=dict(job.get("request") or {}),
        sections={
            "Data and universe": (
                "Daily U.S. equities from the canonical point-in-time research "
                "universe, with SPY as benchmark."
            ),
            "Portfolio construction": (
                "Long-only monthly portfolio targets generated by the registered "
                "strategy configuration."
            ),
            "Execution and costs": (
                "Next-session execution with total recorded costs of "
                f"${float(metrics['total_costs']):,.2f}."
            ),
            "Performance": (
                f"Net CAGR was {float(metrics['cagr']):.2%}, versus a total benchmark "
                f"return of {float(metrics['benchmark_return']):.2%}. Sharpe was "
                f"{float(metrics['sharpe']):.2f}."
            ),
            "Risk": (
                "Annualized volatility was "
                f"{float(metrics['annualized_volatility']):.2%}; maximum drawdown was "
                f"{float(metrics['maximum_drawdown']):.2%}."
            ),
        },
        limitations=(
            "Results are historical and out-of-sample controls do not guarantee "
            "future performance.",
            "Daily data and simplified execution cannot represent intraday "
            "liquidity dynamics.",
            "Current sector labels are not historically effective GICS "
            "classifications.",
            "Taxes, borrow, live order routing, and market microstructure are "
            "outside project scope.",
        ),
    )
    paths = write_research_report(
        report, REPORT_ROOT / "studies" / f"backtest-{experiment_id}"
    )
    root = REPORT_ROOT.resolve()
    return [_item(path.resolve(), root) for path in paths]


def _visible_file(path: Path) -> bool:
    return (
        path.is_file()
        and not path.name.startswith(".")
        and not path.name.endswith(".part")
    )


def _item(path: Path, root: Path) -> ReportItem:
    relative = path.relative_to(root)
    return ReportItem(
        name=path.stem.replace("_", " ").replace("-", " ").title(),
        path=relative.as_posix(),
        category=relative.parts[0] if len(relative.parts) > 1 else "general",
        format=path.suffix.lower().lstrip("."),
        size_bytes=path.stat().st_size,
        updated_at=datetime.fromtimestamp(path.stat().st_mtime, UTC).isoformat(),
    )
